services:
  easyimage:
    image: ghcr.io/lau0x/easyimage:latest
    ports:
      - "8080:80"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./i:/var/www/html/i
      - ./config:/var/www/html/config
      - ./admin/logs:/var/www/html/admin/logs
    restart: unless-stopped
