date.timezone=Asia/Shanghai
expose_php=Off
display_errors=Off
log_errors=On
file_uploads=On
max_execution_time=300
max_input_time=300
memory_limit=512M
post_max_size=64M
session.cookie_httponly=1
session.cookie_samesite=Lax
upload_max_filesize=32M
opcache.enable=1
opcache.validate_timestamps=1
